#use mysql in dev and deploy env
server:
   port: 8082

spring:
   datasource:
      #use the same db user as auth service
      #refrences env from github action workflow
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/account_db
      username: ${MYSQL_USER:authuser}
      password: ${MYSQL_PASSWORD:chenhaotian}
      driver-class-name: com.mysql.cj.jdbc.Driver

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        security:
            enabled: false


