name: CI Pipeline

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: account_db
          MYSQL_USER: authuser
          MYSQL_PASSWORD: chenhaotian
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Wait for MySQL to Start
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for database..."
            sleep 3
          done

      - name: Build and Run Tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: authuser
          MYSQL_PASSWORD: chenhaotian
        run: mvn clean verify
